"""
Meeting and related models
"""

from datetime import datetime, date
from typing import TYPE_CHECKING, Optional, List
import uuid
import enum

from sqlalchemy import String, Text, DateTime, Date, Integer, Float, Enum, ForeignKey, func, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.user import User


class MeetingStatus(str, enum.Enum):
    """Meeting processing status"""
    UPLOADED = "uploaded"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    REVIEW_PENDING = "review_pending"


class ActionItemStatus(str, enum.Enum):
    """Action item completion status"""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"


class ActionItemPriority(str, enum.Enum):
    """Action item priority level"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"


class Meeting(Base):
    """Meeting model - core entity"""
    
    __tablename__ = "meetings"
    
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False
    )
    audio_file_url: Mapped[Optional[str]] = mapped_column(
        String(500),
        nullable=True
    )
    audio_duration: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
        comment="Duration in seconds"
    )
    status: Mapped[MeetingStatus] = mapped_column(
        Enum(MeetingStatus),
        default=MeetingStatus.UPLOADED,
        nullable=False
    )
    meeting_date: Mapped[Optional[date]] = mapped_column(
        Date,
        nullable=True
    )
    error_message: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now()
    )
    
    # Relationships
    user: Mapped["User"] = relationship(
        "User",
        back_populates="meetings"
    )
    summary: Mapped[Optional["MeetingSummary"]] = relationship(
        "MeetingSummary",
        back_populates="meeting",
        uselist=False,
        cascade="all, delete-orphan"
    )
    transcripts: Mapped[List["Transcript"]] = relationship(
        "Transcript",
        back_populates="meeting",
        cascade="all, delete-orphan",
        order_by="Transcript.start_time"
    )
    action_items: Mapped[List["ActionItem"]] = relationship(
        "ActionItem",
        back_populates="meeting",
        cascade="all, delete-orphan"
    )
    
    def __repr__(self) -> str:
        return f"<Meeting {self.title}>"


class MeetingSummary(Base):
    """Meeting summary generated by AI"""
    
    __tablename__ = "meeting_summaries"
    
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4
    )
    meeting_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("meetings.id", ondelete="CASCADE"),
        unique=True,
        nullable=False
    )
    summary: Mapped[str] = mapped_column(
        Text,
        nullable=False
    )
    key_points: Mapped[List[str]] = mapped_column(
        JSON,
        default=list
    )
    decisions: Mapped[List[str]] = mapped_column(
        JSON,
        default=list
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now()
    )
    
    # Relationships
    meeting: Mapped["Meeting"] = relationship(
        "Meeting",
        back_populates="summary"
    )
    
    def __repr__(self) -> str:
        return f"<MeetingSummary for {self.meeting_id}>"


class Transcript(Base):
    """Speech-to-text transcript segments"""
    
    __tablename__ = "transcripts"
    
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4
    )
    meeting_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("meetings.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    speaker: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        default="Unknown"
    )
    text: Mapped[str] = mapped_column(
        Text,
        nullable=False
    )
    start_time: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="Start time in seconds"
    )
    end_time: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="End time in seconds"
    )
    confidence: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
        comment="STT confidence score 0-1"
    )
    
    # Relationships
    meeting: Mapped["Meeting"] = relationship(
        "Meeting",
        back_populates="transcripts"
    )
    
    def __repr__(self) -> str:
        return f"<Transcript {self.speaker}: {self.text[:30]}...>"


class ActionItem(Base):
    """Action items extracted from meetings"""
    
    __tablename__ = "action_items"
    
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4
    )
    meeting_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("meetings.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    content: Mapped[str] = mapped_column(
        Text,
        nullable=False
    )
    assignee: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True
    )
    due_date: Mapped[Optional[date]] = mapped_column(
        Date,
        nullable=True
    )
    priority: Mapped[ActionItemPriority] = mapped_column(
        Enum(ActionItemPriority),
        default=ActionItemPriority.MEDIUM
    )
    status: Mapped[ActionItemStatus] = mapped_column(
        Enum(ActionItemStatus),
        default=ActionItemStatus.PENDING
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now()
    )
    
    # Relationships
    meeting: Mapped["Meeting"] = relationship(
        "Meeting",
        back_populates="action_items"
    )
    
    def __repr__(self) -> str:
        return f"<ActionItem {self.content[:30]}...>"
